### ISSUE TITLE
Rendering of templates fails with foreman develop

### ISSUE THREAD

**Issue by laugmanuel** [dm-drogeriemarkt/foreman_vault#36]
Upstream PR https://github.com/theforeman/foreman/pull/8039 changed the API of template rendering mechanism which causes this plugin to not work with `develop` and upcoming Foreman releases:

```
2020-10-30T12:16:57 [D|app|3bbc2e11] Backtrace for 'Error rendering the Kickstart template' error (ArgumentError): unknown keyword: renderer
/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_vault-0.3.0/app/models/concerns/foreman_vault/provisioning_template_extensions.rb:7:in `render'
/usr/share/foreman/app/controllers/concerns/foreman/controller/template_rendering.rb:18:in `safe_render'
/usr/share/foreman/app/controllers/concerns/foreman/controller/template_rendering.rb:9:in `render_template'
/usr/share/foreman/app/controllers/unattended_controller.rb:130:in `render_provisioning_template'
/usr/share/foreman/app/controllers/unattended_controller.rb:68:in `host_template'
/opt/theforeman/tfm-ror52/root/usr/share/gems/gems/actionpack-5.2.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
[...]
```

We call the changed upstream code here: https://github.com/dm-drogeriemarkt/foreman_vault/blob/master/app/models/concerns/foreman_vault/provisioning_template_extensions.rb#L10

**Comment by laugmanuel** [comment]
Fixed in #37
